Trait {
	#name : #TMAAntServices,
	#instVars : [
		'stage'
	],
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'MolAnts2.0'
}

{ #category : #services }
TMAAntServices >> getRole [

	
]

{ #category : #services }
TMAAntServices >> getRoleName [
]

{ #category : #services }
TMAAntServices >> getStage [
]

{ #category : #services }
TMAAntServices >> getStageName [

	
]
